# Janus Testbed — Scenario 12
# Mode: Tunnel | Enc: AES-128-GCM | Auth: AEAD | DH: 20 (ECP-384) | PFS: ON
# Strong config with DH-20 (384-bit ECP) — RECOMMENDED per RFC 8247

connections {
    janus-s12 {
        version = 2
        local_addrs  = %any
        remote_addrs = %any

        local {
            auth = psk
            id = peer-left-12
        }
        remote {
            auth = psk
            id = peer-right-12
        }

        # AES-128-GCM with ECP-384 (group 20)
        proposals = aes128gcm16-prfsha384-ecp384!

        dpd_delay = 30s
        fragmentation = yes

        children {
            janus-s12-child {
                mode = tunnel

                esp_proposals = aes128gcm16!

                copy_dscp = out
                copy_ecn = yes

                dpd_action = restart
                start_action = start
                close_action = restart

                life_time = 1h
                rekey_time = 48min

                local_ts  = 0.0.0.0/0
                remote_ts = 0.0.0.0/0
            }
        }
    }
}

secrets {
    ike-s12 {
        id-left  = peer-left-12
        id-right = peer-right-12
        secret = "janus-testbed-psk-scenario-12"
    }
}
