# Janus Testbed — Scenario 07
# Mode: TRANSPORT | Enc: AES-256-GCM | Auth: AEAD | DH: 19 | PFS: ON
# Transport mode (no encapsulation of entire IP packet — only payload encrypted)
# Used for host-to-host IPsec without tunneling overhead

connections {
    janus-s07 {
        version = 2
        local_addrs  = %any
        remote_addrs = %any

        local {
            auth = psk
            id = peer-left-07
        }
        remote {
            auth = psk
            id = peer-right-07
        }

        proposals = aes256gcm16-prfsha384-ecp256!

        dpd_delay = 30s
        fragmentation = yes

        children {
            janus-s07-child {
                # TRANSPORT mode — encrypts payload only, not outer IP header
                mode = transport

                esp_proposals = aes256gcm16!

                copy_dscp = out
                copy_ecn = yes

                dpd_action = restart
                start_action = start
                close_action = restart

                life_time = 1h
                rekey_time = 48min

                local_ts  = 0.0.0.0/0
                remote_ts = 0.0.0.0/0
            }
        }
    }
}

secrets {
    ike-s07 {
        id-left  = peer-left-07
        id-right = peer-right-07
        secret = "janus-testbed-psk-scenario-07"
    }
}
