# Janus Testbed — Scenario 04
# Mode: Tunnel | Enc: AES-128-CBC | Auth: HMAC-SHA2-256-128 | DH: 14 (2048-MODP) | PFS: ON
# Similar to S03 but with 128-bit AES — still compliant, lower key strength

connections {
    janus-s04 {
        version = 2
        local_addrs  = %any
        remote_addrs = %any

        local {
            auth = psk
            id = peer-left-04
        }
        remote {
            auth = psk
            id = peer-right-04
        }

        proposals = aes128-sha256-prfsha256-modp2048!

        dpd_delay = 30s
        fragmentation = yes

        children {
            janus-s04-child {
                mode = tunnel

                esp_proposals = aes128-sha256!

                copy_dscp = out
                copy_ecn = yes

                dpd_action = restart
                start_action = start
                close_action = restart

                life_time = 1h
                rekey_time = 48min

                local_ts  = 0.0.0.0/0
                remote_ts = 0.0.0.0/0
            }
        }
    }
}

secrets {
    ike-s04 {
        id-left  = peer-left-04
        id-right = peer-right-04
        secret = "janus-testbed-psk-scenario-04"
    }
}
