# Janus Testbed — Scenario 10
# Mode: Tunnel | Enc: AES-256-CBC | Auth: HMAC-SHA1-96 | DH: 14 | PFS: ON
# Mixed quality: good cipher + deprecated auth algorithm
# SHA1-96 → MUST- (deprecated, collision risk, Medium/High risk per RFC 8221)

connections {
    janus-s10 {
        version = 2
        local_addrs  = %any
        remote_addrs = %any

        local {
            auth = psk
            id = peer-left-10
        }
        remote {
            auth = psk
            id = peer-right-10
        }

        proposals = aes256-sha1-prfsha1-modp2048!

        dpd_delay = 30s
        fragmentation = yes

        children {
            janus-s10-child {
                mode = tunnel

                # AES-256-CBC is MUST (legacy) but HMAC-SHA1-96 is deprecated (MUST-)
                esp_proposals = aes256-sha1!

                copy_dscp = out
                copy_ecn = yes

                dpd_action = restart
                start_action = start
                close_action = restart

                life_time = 1h
                rekey_time = 48min

                local_ts  = 0.0.0.0/0
                remote_ts = 0.0.0.0/0
            }
        }
    }
}

secrets {
    ike-s10 {
        id-left  = peer-left-10
        id-right = peer-right-10
        secret = "janus-testbed-psk-scenario-10"
    }
}
